<?php
    global $gAr;
    foreach($gAr as $k=>$v){${$k}=$v;}
?>
 
<table class="table table-borderd">
    <thead>
        <tr>
            <td>#</td>
            <td>Title</td> 
            <td>Code</td> 
            <td>Action </td> 
        </tr>
    </thead>
    <tbody class="details_products">
        <?php
            $sr=1;
            foreach($base as $u){ 
            ?>
            <tr>
                <td><?=$sr++?></td>
                <td><?=$u['title']?></td>
                <td><?=$u['code']?></td>
                <td><input <?php if(in_array($u['id'],$all_assign)){?>checked="checked"<?php } ?> type="checkbox" class="base-checkbox" name="base_checkbox[]" value="<?= $u['id'] ?>"></td>    
            </tr>

            <?php 
            }
        ?>
    </tbody> 
</table>
