<script>
    
$(document).on('click','.voucher_details_load',function(){
    const voucher_id = $(this).attr('data-id');
    console.log('d')
    console.log({voucher_id});
    $('#voucher_details_body').html(loadingImage)
    $.ajax({
        type:'post',
        url:ajUrl,
        data:{voucher_details:1,voucher_id:voucher_id},
        success:function(data){
            if(typeof(data.status)  !== "undefined"){ 
                if(data.status==1){
                    $('#voucher_details_body').html(data.html);
                }
                swMessageFromJs(data.m);
            }   
            else{
                swMessage(AJAX_ERROR_MESSAGE);    
            }
        },
        error:function(data){
            swMessage(AJAX_ERROR_MESSAGE);  
        }
    });
    $('#voucher_details_modal_btn').click();
});
</script>

<div style="display: none;">
    <button data-toggle="modal" data-target="#voucher_details_modal" id="voucher_details_modal_btn"></button>
</div>


<div class="modal fade" id="voucher_details_modal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Voucher details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="voucher_details_body"></div>
        </div>
    </div>
</div>